#creating a ci githubaction workflow for automatic building and pushing of docker images to dockerhub
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/backend:latest
      - name: Build and push frontend image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/frontend:latest
#add a job that update the new image tag in helm values.yaml file and then commit and push the changes to the repository
  update-helm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update backend image tag in Helm values.yaml
        run: |
          sed -i "s|repository: infhari/backend|repository: ${{ secrets.DOCKER_USERNAME }}/backend|g" backend-helm/values.yaml
          sed -i "s|tag:.*|tag: \"${{ github.sha }}\"|g" backend-helm/values.yaml

      - name: Update frontend image tag in Helm values.yaml
        run: |
          sed -i "s|repository: infhari/frontend|repository: ${{ secrets.DOCKER_USERNAME }}/frontend|g" frontend-helm/values.yaml
          sed -i "s|tag:.*|tag: \"${{ github.sha }}\"|g" frontend-helm/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name "sreehari0418-prog"
          git config --global user.email "sreehari0418@gmail.com"
          git add backend-helm/values.yaml frontend-helm/values.yaml
          git commit -m "Update image tags in Helm values.yaml"
          git push origin main