#creating a ci githubaction workflow for automatic building and pushing of docker images to dockerhub
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v7
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.sha }}
                ${{ secrets.DOCKER_USERNAME }}/backend:latest
      - name: Build and push frontend image
        uses: docker/build-push-action@v7
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.sha }}
                ${{ secrets.DOCKER_USERNAME }}/frontend:latest
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: deploy frontend
        run: |
          helm upgrade --install frontend ./frontend-helm --set image.repository=${{ secrets.DOCKER_USERNAME }}/frontend --set image.tag=${{ github.sha }}

      - name: deploy backend
        run: |
          helm upgrade --install backend ./backend-helm --set image.repository=${{ secrets.DOCKER_USERNAME }}/backend --set image.tag=${{ github.sha }}      

